apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-go-ihwcjinb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-go-ihwcjinb 
  name: backend-tests-go-ihwcjinb
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-go-ihwcjinb 
